# TODO: What are these codes used for? add Doc string
class ResponseCodes:
    SUCCESS = '000'
    FAIL = '-1'
    NO_DATA_FOUND = '001'
    NODE_ALREADY_EXECUTING = '002'
    INVALID_ARGUMENTS = '003'
    INVALID_TASK_DEFINITION = '004'
    RESPONSE_NOT_RECEIVED_FROM_SCHEDULER = '005'
    EXECUTION_TIME_NOT_REACHED = '006'
    EXECUTION_INTRUPTED_BY_CONTROLLER = '007'
    UNABLE_TO_INITIALIZE_TASK = '008'

    SYSTEM_MALFUNCTION = '051'
    DB_MALFUNCTION = '052'
    INVALID_TRANS = '12'
    NOT_APPROVED = 'NA'
    APPROVED = '00'
    APPROVED_DESC = 'Approved'
